version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - OPENWEATHER_API_KEY=043f4328cde7d9cecc8654622948723f
    networks:
      - myweatherapp_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - myweatherapp_network

networks:
  myweatherapp_network:
    driver: bridge

